OPENSIPSTACKDIR	= ../opensipstack
HAS_RTBECLIENT = 0

PROG  := opensbc

SOURCES := Main.cxx
SOURCES += SBCCallHandler.cxx
SOURCES += SBCRoutingHandler.cxx
SOURCES += SBCAuthHandler.cxx
SOURCES += OpenSBC.cxx
SOURCES += Router.cxx
SOURCES += RouteRecord.cxx

include ../opensipstack/make/opensipstack.mak









